language: go
go:
  - 1.3
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - ./scripts/test

before_install:
  - RepoName=`basename $PWD`
  - SrcDir=`dirname $PWD`
  - DestDir="`dirname $SrcDir`/cloudfoundry"
  - mv $SrcDir $DestDir
  - cd ../../cloudfoundry/$RepoName
